-- ============================================================================
-- BLUP test 39 · The seat survives the sale
-- ============================================================================
-- Test 18 proved the plan and the hold. This proves the part that was missing
-- underneath it: that the chair the buyer picked is still theirs after the
-- basket becomes an order, after the payment page, and after the ticket is
-- issued — and that nobody else can be sold it at any point along the way.
--
-- What is actually being proved here:
--
--   · a held seat stays held when the basket turns into orders
--   · the paid ticket names the seat, so the door knows where to send them
--   · an abandoned checkout gives the seat back, without a sweep having to run
--   · a numbered sector cannot be bought without naming a seat — the hole the
--     guest checkout and the plain ticket list both walked straight through
--   · a seat cannot be bought through the wrong sector
--   · two live orders cannot name one seat, whatever the app does
--   · holding four seats is all-or-nothing
--   · "give me four together" gives four together, front and centre, and never
--     quietly hands out a wheelchair space
--   · regenerating a stand cannot delete a seat somebody paid for
--   · a sector can be renamed, and cannot be re-pointed once it has sold
--   · the door list knows who is in D14
-- ============================================================================
\set ON_ERROR_STOP on

begin;

insert into auth.users (id, email, raw_user_meta_data) values
  ('a3939393-0000-0000-0000-000000000001', 'org39@example.com',    '{"display_name":"Org"}'),
  ('a3939393-0000-0000-0000-000000000002', 'buyer39@example.com',  '{"display_name":"Buyer"}'),
  ('a3939393-0000-0000-0000-000000000003', 'rival39@example.com',  '{"display_name":"Rival"}'),
  ('a3939393-0000-0000-0000-000000000004', 'stranger39@example.com', '{"display_name":"Stranger"}'),
  -- Plans are drawn by BLUP, not by the organizer (migration 0070). The
  -- organizer below is deliberately NOT one, so the refusals are real.
  ('a3939393-0000-0000-0000-000000000009', 'admin39@example.com', '{"display_name":"Admin"}');

update public.profiles set app_role = 'admin' where id = 'a3939393-0000-0000-0000-000000000009';
select set_config('request.jwt.claim.sub', 'a3939393-0000-0000-0000-000000000009', true);

insert into public.organizations (id, name, slug, created_by, verification_status, payouts_enabled)
values ('d3939393-0000-0000-0000-000000000001', 'Divadlo 39', 'divadlo-39',
        'a3939393-0000-0000-0000-000000000001', 'verified', true);

insert into public.venue_maps (id, organization_id, name, image_width, image_height, created_by)
values ('f3939393-0000-0000-0000-000000000001', 'd3939393-0000-0000-0000-000000000001',
        'Hľadisko', 1600, 1200, 'a3939393-0000-0000-0000-000000000001');

insert into public.events (id, creator_id, organization_id, title, category, start_at,
                           latitude, longitude, is_free, price_cents, status, venue_map_id)
values ('d3939393-0000-0000-0000-000000000002', 'a3939393-0000-0000-0000-000000000001',
        'd3939393-0000-0000-0000-000000000001', 'Premiéra', 'theatre',
        now() + interval '30 days', 48.1486, 17.1077, false, 2000, 'published',
        'f3939393-0000-0000-0000-000000000001');

insert into public.ticket_types (id, event_id, name, price_cents, quantity_total, max_per_order)
values
  ('c3939393-0000-0000-0000-000000000001', 'd3939393-0000-0000-0000-000000000002',
   'Prízemie', 2000, 50, 20),
  ('c3939393-0000-0000-0000-000000000002', 'd3939393-0000-0000-0000-000000000002',
   'Balkón', 1200, 50, 20);

insert into public.venue_sections (id, venue_map_id, ticket_type_id, name, x, y, width, height, sort_order)
values
  ('b3939393-0000-0000-0000-000000000001', 'f3939393-0000-0000-0000-000000000001',
   'c3939393-0000-0000-0000-000000000001', 'Prízemie', 0.1, 0.4, 0.8, 0.5, 0),
  ('b3939393-0000-0000-0000-000000000002', 'f3939393-0000-0000-0000-000000000001',
   'c3939393-0000-0000-0000-000000000002', 'Balkón', 0.1, 0.1, 0.8, 0.2, 1);

-- Prízemie: three rows of six, generated by the database rather than the app.
do $$
declare
  made jsonb;
begin
  perform set_config('request.jwt.claim.sub', 'a3939393-0000-0000-0000-000000000009', true);
  made := public.generate_section_seats('b3939393-0000-0000-0000-000000000001', 3, 6);
  assert (made ->> 'total')::int = 18, format('three rows of six is eighteen, got %s', made ->> 'total');
  assert (made ->> 'created')::int = 18, 'and all eighteen are new';
  raise notice 'PASS a stand is generated from the database, rows lettered from the front';
end $$;

-- Balkón stays an open sector: no seats, sells by count.


-- ============================================================================
-- 1. The seat travels: basket -> order -> ticket
-- ============================================================================
do $$
declare
  buyer uuid := 'a3939393-0000-0000-0000-000000000002';
  rival uuid := 'a3939393-0000-0000-0000-000000000003';
  ev    uuid := 'd3939393-0000-0000-0000-000000000002';
  seat  uuid;
  co    public.checkouts;
  tick  public.tickets;
  map   jsonb;
  sect  jsonb;
  dot   jsonb;
begin
  select id into seat from public.venue_seats
  where venue_section_id = 'b3939393-0000-0000-0000-000000000001'
    and row_label = 'B' and seat_number = 3;

  perform set_config('request.jwt.claim.sub', buyer::text, true);
  perform public.cart_hold_seat(seat);

  co := public.create_checkout(buyer, null);

  -- The basket is gone — that is what create_checkout does — so if the seat
  -- lived only on the cart line, this is the moment it went back on sale.
  assert not exists (select 1 from public.cart_items where user_id = buyer),
    'the basket is emptied into the checkout';

  assert exists (
    select 1 from public.orders o
    where o.checkout_id = co.id and o.venue_seat_id = seat and o.quantity = 1
  ), 'the order names the seat';
  raise notice 'PASS the seat survives the basket becoming an order';

  -- And it is gone for the person refreshing the plan right now.
  perform set_config('request.jwt.claim.sub', rival::text, true);
  begin
    perform public.cart_hold_seat(seat);
    assert false, 'a seat on a live order must not be holdable';
  exception when others then
    assert sqlerrm = 'SEAT_TAKEN', format('expected SEAT_TAKEN, got %s', sqlerrm);
  end;
  raise notice 'PASS a seat being paid for is not on sale';

  -- ---- paid ------------------------------------------------------------------
  perform public.fulfill_checkout(co.id, 'stripe', 'pi_seat_39', co.total_cents);

  select * into tick from public.tickets t
  where t.event_id = ev and t.buyer_id = buyer limit 1;

  assert tick.venue_seat_id = seat,
    format('the ticket must name the seat, got %s', coalesce(tick.venue_seat_id::text, 'null'));
  raise notice 'PASS the paid ticket names the chair the buyer picked';

  -- ---- and the plan tells the buyer it is theirs ----------------------------
  perform set_config('request.jwt.claim.sub', buyer::text, true);
  -- Since migration 0070 the seats come per sector rather than inline in the
  -- map: a stadium does not fit in one document.
  map  := public.seat_map_for_event(ev);
  sect := (select s from jsonb_array_elements(map -> 'sections') s where s ->> 'name' = 'Prízemie');
  dot  := (select d
           from jsonb_array_elements(public.section_seats(ev, (sect ->> 'id')::uuid)) d
           where (d ->> 'id')::uuid = seat);

  assert (dot ->> 'mine')::boolean, 'my own seat is mine';
  assert dot ->> 'mine_claim' = 'sold', 'and it is sold, not merely held';
  assert not (dot ->> 'taken')::boolean, 'a seat I own is not "taken" from me';
  assert not (dot ->> 'free')::boolean, 'nor is it free';
  raise notice 'PASS a seat you bought reads differently from one you are holding';

  perform set_config('request.jwt.claim.sub', rival::text, true);
  map  := public.seat_map_for_event(ev);
  sect := (select s from jsonb_array_elements(map -> 'sections') s where s ->> 'name' = 'Prízemie');
  dot  := (select d
           from jsonb_array_elements(public.section_seats(ev, (sect ->> 'id')::uuid)) d
           where (d ->> 'id')::uuid = seat);
  assert (dot ->> 'taken')::boolean and not (dot ->> 'mine')::boolean,
    'and to everybody else it is simply taken';
  raise notice 'PASS somebody else sees the same seat as taken, and as nobody''s business whose';
end $$;


-- ============================================================================
-- 2. An abandoned payment gives the chair back
-- ============================================================================
do $$
declare
  buyer uuid := 'a3939393-0000-0000-0000-000000000002';
  rival uuid := 'a3939393-0000-0000-0000-000000000003';
  seat  uuid;
  co    public.checkouts;
begin
  select id into seat from public.venue_seats
  where venue_section_id = 'b3939393-0000-0000-0000-000000000001'
    and row_label = 'C' and seat_number = 1;

  perform set_config('request.jwt.claim.sub', buyer::text, true);
  perform public.cart_hold_seat(seat);
  co := public.create_checkout(buyer, null);

  -- They closed the tab. Half an hour later:
  update public.orders set expires_at = now() - interval '1 minute' where checkout_id = co.id;
  update public.checkouts set expires_at = now() - interval '1 minute' where id = co.id;
  perform public.release_expired_holds();

  perform set_config('request.jwt.claim.sub', rival::text, true);
  perform public.cart_hold_seat(seat);
  assert exists (select 1 from public.cart_items
                 where venue_seat_id = seat and user_id = rival and expires_at > now()),
    'an abandoned checkout must release its seat';
  raise notice 'PASS a seat is not lost forever to somebody who closed the tab';

  delete from public.cart_items where venue_seat_id = seat;
end $$;


-- ============================================================================
-- 3. A numbered sector cannot be bought blind
-- ============================================================================
-- This is the hole the guest checkout walked through: it calls create_order()
-- with a ticket type and a quantity and never sees a plan. Before this, that
-- produced a valid ticket to a numbered stand with no seat on it.
do $$
declare
  buyer  uuid := 'a3939393-0000-0000-0000-000000000002';
  stalls uuid := 'c3939393-0000-0000-0000-000000000001';
  balcony uuid := 'c3939393-0000-0000-0000-000000000002';
  seat   uuid;
  ord    public.orders;
begin
  begin
    ord := public.create_order(buyer, stalls, 1);
    assert false, 'a numbered sector must not sell without a seat';
  exception when others then
    assert sqlerrm = 'SEAT_REQUIRED', format('expected SEAT_REQUIRED, got %s', sqlerrm);
  end;

  -- The same through a guest's address, which is the path that actually shipped.
  begin
    ord := public.create_order(null, stalls, 1, null, null, null, null, 'hostka@example.com', 'Hosťka');
    assert false, 'and not to a guest either';
  exception when others then
    assert sqlerrm = 'SEAT_REQUIRED', format('expected SEAT_REQUIRED, got %s', sqlerrm);
  end;
  raise notice 'PASS a numbered sector refuses to sell a ticket with no chair on it';

  -- The basket is the third door into the same room.
  perform set_config('request.jwt.claim.sub', buyer::text, true);
  begin
    perform public.cart_add(stalls, 2);
    assert false, 'and the plain ticket list must not offer it either';
  exception when others then
    assert sqlerrm = 'SEAT_REQUIRED', format('expected SEAT_REQUIRED, got %s', sqlerrm);
  end;
  raise notice 'PASS the plain ticket list cannot sell a numbered stand by the metre';

  -- An open sector is untouched: this is the common case and must still work.
  perform public.cart_add(balcony, 2);
  assert exists (select 1 from public.cart_items
                 where user_id = buyer and ticket_type_id = balcony and quantity = 2),
    'an open sector still sells by count';
  perform public.cart_clear();
  raise notice 'PASS a sector without seats is unaffected';

  -- ---- and a seat can only be bought through its own sector ------------------
  select id into seat from public.venue_seats
  where venue_section_id = 'b3939393-0000-0000-0000-000000000001'
    and row_label = 'A' and seat_number = 1;

  begin
    ord := public.create_order(buyer, balcony, 1, null, null, null, null, null, null, null, null, null, seat);
    assert false, 'a stalls seat cannot be bought on a balcony ticket';
  exception when others then
    assert sqlerrm = 'SEAT_WRONG_SECTION', format('expected SEAT_WRONG_SECTION, got %s', sqlerrm);
  end;
  raise notice 'PASS a seat cannot be bought through the wrong sector';
end $$;


-- ============================================================================
-- 4. Two live orders, one chair
-- ============================================================================
do $$
declare
  buyer  uuid := 'a3939393-0000-0000-0000-000000000002';
  rival  uuid := 'a3939393-0000-0000-0000-000000000003';
  stalls uuid := 'c3939393-0000-0000-0000-000000000001';
  seat   uuid;
  ord    public.orders;
begin
  select id into seat from public.venue_seats
  where venue_section_id = 'b3939393-0000-0000-0000-000000000001'
    and row_label = 'A' and seat_number = 2;

  ord := public.create_order(buyer, stalls, 1, null, null, null, null, null, null, null, null, null, seat);
  assert ord.venue_seat_id = seat, 'the order carries the seat';

  -- The function's own check should catch this. The index is what catches it
  -- when two of these run at the same instant, so both are worth proving.
  begin
    ord := public.create_order(rival, stalls, 1, null, null, null, null, null, null, null, null, null, seat);
    assert false, 'a seat on a live order must not be orderable again';
  exception when others then
    assert sqlerrm in ('SEAT_TAKEN', 'duplicate key value violates unique constraint "orders_seat_once"')
        or sqlerrm like '%orders_seat_once%',
      format('expected the seat to be refused, got %s', sqlerrm);
  end;
  raise notice 'PASS one chair cannot be on two live orders';

  -- Cancelled, and it is back.
  update public.orders set payment_status = 'cancelled' where venue_seat_id = seat;
  ord := public.create_order(rival, stalls, 1, null, null, null, null, null, null, null, null, null, seat);
  assert ord.venue_seat_id = seat, 'a cancelled order releases its seat';
  update public.orders set payment_status = 'cancelled' where venue_seat_id = seat;
  raise notice 'PASS a cancelled order puts the chair back on sale';

  -- And three of one chair is not a thing.
  begin
    ord := public.create_order(buyer, stalls, 3, null, null, null, null, null, null, null, null, null, seat);
    assert false, 'three of seat A2 is not a purchase';
  exception when others then
    assert sqlerrm = 'SEAT_IS_SINGLE', format('expected SEAT_IS_SINGLE, got %s', sqlerrm);
  end;
  raise notice 'PASS a seat is one seat';
end $$;


-- ============================================================================
-- 5. Four seats, all or nothing
-- ============================================================================
do $$
declare
  buyer uuid := 'a3939393-0000-0000-0000-000000000002';
  rival uuid := 'a3939393-0000-0000-0000-000000000003';
  wanted uuid[];
  blocked uuid;
  n integer;
begin
  select array_agg(id order by seat_number) into wanted
  from public.venue_seats
  where venue_section_id = 'b3939393-0000-0000-0000-000000000001'
    and row_label = 'C' and seat_number between 2 and 5;

  blocked := wanted[3];

  perform set_config('request.jwt.claim.sub', rival::text, true);
  perform public.cart_hold_seat(blocked);

  perform set_config('request.jwt.claim.sub', buyer::text, true);
  begin
    perform public.cart_hold_seats(wanted);
    assert false, 'one seat gone must fail the whole set';
  exception when others then
    assert sqlerrm = 'SEAT_HELD', format('expected SEAT_HELD, got %s', sqlerrm);
  end;

  select count(*) into n from public.cart_items where user_id = buyer and expires_at > now();
  assert n = 0, format('nothing may be held when the set fails, got %s', n);
  raise notice 'PASS holding four seats is all of them or none';

  -- The rival lets go, and now the whole row is free.
  perform public.cart_release_seat(blocked);   -- runs as buyer: not theirs
  assert exists (select 1 from public.cart_items where venue_seat_id = blocked),
    'releasing somebody else''s seat does nothing';

  perform set_config('request.jwt.claim.sub', rival::text, true);
  perform public.cart_release_seat(blocked);

  perform set_config('request.jwt.claim.sub', buyer::text, true);
  perform public.cart_hold_seats(wanted);
  select count(*) into n from public.cart_items where user_id = buyer and expires_at > now();
  assert n = 4, format('four seats, four lines, got %s', n);

  -- Clicking the same four again is impatience, not an error.
  perform public.cart_hold_seats(wanted);
  select count(*) into n from public.cart_items where user_id = buyer and expires_at > now();
  assert n = 4, format('re-holding the same four changes nothing, got %s', n);
  raise notice 'PASS four seats in one go, and asking twice is not an error';

  perform public.cart_clear();
end $$;


-- ============================================================================
-- 6. "Give me four together"
-- ============================================================================
do $$
declare
  buyer   uuid := 'a3939393-0000-0000-0000-000000000002';
  stalls  uuid := 'b3939393-0000-0000-0000-000000000001';
  picked  record;
  rows_n  integer;
  labels  text[];
  numbers integer[];
begin
  -- An empty house: the best four are in the front row, in the middle.
  select array_agg(s.row_label order by s.seat_number),
         array_agg(s.seat_number order by s.seat_number)
    into labels, numbers
  from public.suggest_seats(stalls, 4) s;

  assert array_length(labels, 1) = 4, 'four asked for, four offered';
  select count(distinct l) into rows_n from unnest(labels) l;
  assert rows_n = 1, 'and all in one row';
  assert labels[1] = 'A', format('the front row first, got %s', labels[1]);
  assert numbers = array[2, 3, 4, 5],
    format('and centred in a row of six, got %s', numbers::text);
  raise notice 'PASS the suggestion is four together, front and centre';

  -- Take the middle of row A out, and the answer moves to the next row rather
  -- than splitting the group.
  perform set_config('request.jwt.claim.sub', buyer::text, true);
  perform public.cart_hold_seat((select id from public.venue_seats
    where venue_section_id = stalls and row_label = 'A' and seat_number = 3));

  select array_agg(s.row_label order by s.seat_number),
         array_agg(s.seat_number order by s.seat_number)
    into labels, numbers
  from public.suggest_seats(stalls, 4) s;

  select count(distinct l) into rows_n from unnest(labels) l;
  assert rows_n = 1, 'the group is still kept together';
  -- Row A has a hole in the middle now, and row B lost seat 3 to the sale at
  -- the top of this file — so the first row that can still seat four is C.
  assert labels[1] = 'C', format('expected the group moved back to row C, got %s', labels[1]);
  raise notice 'PASS the group is moved back a row rather than split up';

  perform public.cart_clear();

  -- A wheelchair space is never handed out as one of a block.
  perform set_config('request.jwt.claim.sub', 'a3939393-0000-0000-0000-000000000009', true);
  perform public.set_seat_state(
    array[(select id from public.venue_seats
           where venue_section_id = stalls and row_label = 'A' and seat_number = 4)],
    null, 'wheelchair', 'Miesto pre vozík');

  select array_agg(s.seat_number order by s.seat_number) into numbers
  from public.suggest_seats(stalls, 3) s
  where s.row_label = 'A';
  assert numbers is null or not (4 = any (numbers)),
    'a wheelchair space must never be handed out as part of a block';
  raise notice 'PASS an accessible seat is not quietly sold to a group of three';

  -- And a group too big for the room is told so, rather than offered less.
  assert not exists (select 1 from public.suggest_seats(stalls, 9)),
    'nine together in a row of six is nothing, not "here are six"';
  raise notice 'PASS a group that cannot sit together is told nothing, not fobbed off';
end $$;


-- ============================================================================
-- 7. Rebuilding a stand cannot lose a paid seat
-- ============================================================================
do $$
declare
  admin  uuid := 'a3939393-0000-0000-0000-000000000009';
  org    uuid := 'a3939393-0000-0000-0000-000000000001';
  other  uuid := 'a3939393-0000-0000-0000-000000000004';
  stalls uuid := 'b3939393-0000-0000-0000-000000000001';
  kept   uuid;
  made   jsonb;
begin
  perform set_config('request.jwt.claim.sub', admin::text, true);

  -- Row B seat 3 was sold at the top of this test.
  begin
    made := public.generate_section_seats(stalls, 1, 6);
    assert false, 'shrinking a stand must not delete a sold seat';
  exception when others then
    assert sqlerrm = 'SEATS_IN_USE', format('expected SEATS_IN_USE, got %s', sqlerrm);
  end;
  assert (select count(*) from public.venue_seats where venue_section_id = stalls) = 18,
    'and a refusal must change nothing';
  raise notice 'PASS a stand cannot be rebuilt out from under a ticket somebody paid for';

  -- Growing it is free, and the seats that survive keep what they are.
  select id into kept from public.venue_seats
  where venue_section_id = stalls and row_label = 'A' and seat_number = 4;

  made := public.generate_section_seats(stalls, 4, 6);
  assert (made ->> 'total')::int = 24, format('four rows of six, got %s', made ->> 'total');
  assert (made ->> 'removed')::int = 0, 'nothing is thrown away by growing';
  assert (select kind from public.venue_seats where id = kept) = 'wheelchair',
    'and the wheelchair space is still a wheelchair space';
  raise notice 'PASS growing a stand keeps every seat''s identity';

  -- Only BLUP draws a plan. Not a stranger — and, since migration 0070, not the
  -- organizer either: a sector ten pixels wrong sells the wrong seat, and a
  -- sector pointed at the wrong ticket type sells the wrong price.
  perform set_config('request.jwt.claim.sub', other::text, true);
  begin
    made := public.generate_section_seats(stalls, 2, 2);
    assert false, 'a stranger must not rebuild somebody else''s hall';
  exception when others then
    assert sqlerrm = 'VENUE_PLAN_IS_ADMIN_ONLY',
      format('expected VENUE_PLAN_IS_ADMIN_ONLY, got %s', sqlerrm);
  end;

  perform set_config('request.jwt.claim.sub', org::text, true);
  begin
    perform public.update_section(stalls, 'Moje');
    assert false, 'and neither may the organizer whose event it is';
  exception when others then
    assert sqlerrm = 'VENUE_PLAN_IS_ADMIN_ONLY',
      format('expected VENUE_PLAN_IS_ADMIN_ONLY, got %s', sqlerrm);
  end;
  raise notice 'PASS a plan is drawn by BLUP — not by a stranger and not by the organizer';
end $$;


-- ============================================================================
-- 8. Editing a sector
-- ============================================================================
do $$
declare
  admin   uuid := 'a3939393-0000-0000-0000-000000000009';
  stalls  uuid := 'b3939393-0000-0000-0000-000000000001';
  balcony uuid := 'c3939393-0000-0000-0000-000000000002';
  sect    public.venue_sections;
begin
  perform set_config('request.jwt.claim.sub', admin::text, true);

  sect := public.update_section(stalls, 'Prízemie ľavé', '#FF4D8D');
  assert sect.name = 'Prízemie ľavé', 'a sector can be renamed';
  assert sect.colour = '#FF4D8D', 'and recoloured';
  assert sect.x = 0.1, 'and what was not sent is left alone';
  raise notice 'PASS a sector can be corrected without being deleted';

  begin
    sect := public.update_section(stalls, null, null, balcony);
    assert false, 'a sold sector must not change what it sells';
  exception when others then
    assert sqlerrm = 'SEATS_IN_USE', format('expected SEATS_IN_USE, got %s', sqlerrm);
  end;
  raise notice 'PASS a sector that has sold cannot be re-pointed at another ticket type';

  -- Blocking a seat somebody is sitting in is refused rather than pretended.
  begin
    perform public.set_seat_state(
      array[(select venue_seat_id from public.tickets
             where event_id = 'd3939393-0000-0000-0000-000000000002'
               and venue_seat_id is not null limit 1)],
      false);
    assert false, 'a sold seat cannot be taken out of sale';
  exception when others then
    assert sqlerrm = 'SEATS_IN_USE', format('expected SEATS_IN_USE, got %s', sqlerrm);
  end;
  raise notice 'PASS taking a seat out of sale does not un-sell it';
end $$;


-- ============================================================================
-- 9. The door
-- ============================================================================
do $$
declare
  org      uuid := 'a3939393-0000-0000-0000-000000000001';
  stranger uuid := 'a3939393-0000-0000-0000-000000000004';
  ev       uuid := 'd3939393-0000-0000-0000-000000000002';
  label    text;
  n        integer;
  ordered  text[];
begin
  perform set_config('request.jwt.claim.sub', org::text, true);

  select h.seat_label into label
  from public.event_ticket_holders(ev) h
  where h.seat_label is not null limit 1;
  assert label like 'Prízemie%rad B, miesto 3', format('the door list names the seat, got %s', label);
  raise notice 'PASS the attendee list says where the person is sitting';

  select count(*) into n from public.event_ticket_holders(ev, 'B3');
  assert n = 1, format('searching "B3" must find the person in B3, got %s', n);
  raise notice 'PASS at the door people are found by their seat';

  -- The manifest walks the room, not the order book.
  select array_agg(m.row_label || m.seat_number::text) into ordered
  from (select * from public.event_seat_manifest(ev) limit 8) m;
  assert ordered[1] = 'A1' and ordered[8] = 'B2',
    format('the manifest is walked sector, row, seat; got %s', ordered::text);
  assert exists (select 1 from public.event_seat_manifest(ev)
                 where row_label = 'B' and seat_number = 3 and code is not null),
    'and a sold seat carries its ticket';
  assert exists (select 1 from public.event_seat_manifest(ev)
                 where row_label = 'A' and seat_number = 1 and code is null),
    'while an empty one is simply empty';
  raise notice 'PASS the seating list is ordered the way the room is walked';

  perform set_config('request.jwt.claim.sub', stranger::text, true);
  begin
    perform public.event_seat_manifest(ev);
    assert false, 'the seating list is not public';
  exception when others then
    assert sqlerrm <> '', 'a stranger is refused';
  end;
  raise notice 'PASS who sits where is the organizer''s business';
end $$;

rollback;
