import React from 'react';
import { ScrollViewStyleReset } from 'expo-router/html';
import type { PropsWithChildren } from 'react';

/**
 * The HTML shell for the web build.
 *
 * Only rendered at build time in Node, never in the browser — so nothing here
 * has access to the DOM or to app state. Its job is the things a single-page
 * app cannot set from inside React: the document language, the theme colour the
 * browser paints its chrome with, and the card that appears when somebody
 * pastes a Blup link into a chat.
 */
const TITLE = 'Blup — eventy okolo teba';
const DESCRIPTION =
  'Nájdi, čo sa dnes deje v tvojom meste, kúp si lístok na jednom mieste a choď tam s ľuďmi, ' +
  'ktorých poznáš.';
const URL = process.env.EXPO_PUBLIC_WEB_URL ?? 'https://blup.sk';

export default function Root({ children }: PropsWithChildren) {
  return (
    <html lang="sk">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        {/* viewport-fit=cover so the layout reaches under a phone's notch */}
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover"
        />

        <title>{TITLE}</title>
        <meta name="description" content={DESCRIPTION} />
        <meta name="theme-color" content="#0A0D12" />
        <meta name="color-scheme" content="dark" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="Blup" />

        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Blup" />
        <meta property="og:title" content={TITLE} />
        <meta property="og:description" content={DESCRIPTION} />
        <meta property="og:url" content={URL} />
        <meta property="og:image" content={`${URL}/og.png`} />
        <meta property="og:locale" content="sk_SK" />
        <meta name="twitter:card" content="summary_large_image" />

        {/*
          The two faces that carry the first screen, fetched in parallel with
          the bundle instead of after it. Everything else in FONT_CSS is
          discovered normally — preloading all seven would compete with the
          JavaScript for the same few hundred kilobits.
        */}
        <link
          rel="preload"
          href="/fonts/Nunito_900Black.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/Nunito_600SemiBold.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />

        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/manifest.webmanifest" />

        {/*
          Disables the body scroll that react-native-web's ScrollView would
          otherwise fight with — without it the page scrolls twice, once inside
          the app and once outside it.
        */}
        <ScrollViewStyleReset />

        {/*
          Backend configuration, loaded before the bundle so it can override
          what was baked in at export time.

          Why it exists: a web build hard-codes whatever EXPO_PUBLIC_SUPABASE_URL
          was set when it was made. Upload a build that was exported against a
          local backend and the site loads perfectly and talks to nothing — it
          is the quietest possible failure. With this file the same archive can
          be pointed at a project by editing one line on the hosting, no build
          tools involved. Everything in it is public by construction; it ships
          in the JavaScript either way.
        */}
        <script src="/blup-config.js" />

        <style dangerouslySetInnerHTML={{ __html: FONT_CSS }} />
        <style dangerouslySetInnerHTML={{ __html: SHELL_CSS }} />
      </head>
      <body>{children}</body>
    </html>
  );
}

/**
 * The type, on the web, as CSS rather than as JavaScript.
 *
 * `useFonts` from @expo-google-fonts downloads a .ttf per weight and holds the
 * whole app behind them — seven files, 870 kB, and not one letter on screen
 * until the last of them lands. A .ttf is a format for an operating system; a
 * browser wants .woff2, which has brotli built in.
 *
 * So the web loads the same seven faces as woff2, subset to latin + latin-ext
 * (which is where ľ ť ď ň ô č š ž live), from mobile/public/fonts —
 * 149 kB for the set instead of 870 kB, generated by scripts/make-webfonts.mjs.
 *
 * `font-display: swap` is the other half of the fix: the text is readable in a
 * system face immediately and re-renders in Nunito when it arrives, rather than
 * the page staying blank while it downloads. The family names are exactly the
 * ones in theme/fontFamily, so nothing in the app changes.
 */
const FONT_FACES = [
  'Nunito_400Regular', 'Nunito_600SemiBold', 'Nunito_700Bold',
  'Nunito_800ExtraBold', 'Nunito_900Black',
  'JetBrainsMono_400Regular', 'JetBrainsMono_600SemiBold',
];

const FONT_CSS = FONT_FACES.map((name) => `
  @font-face {
    font-family: '${name}';
    src: url('/fonts/${name}.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
    font-display: swap;
  }`).join('\n');

/**
 * The ground the app is painted on. Set here as well as in the app so the page
 * is never white for the moment between first paint and hydration — on a dark
 * product that flash reads as a broken page.
 */
const SHELL_CSS = `
  html, body { background-color: #0A0D12; color-scheme: dark; }
  body {
    overscroll-behavior-y: none;
    -webkit-font-smoothing: antialiased;
    /* Stop the grey flash on tap that makes a web app feel like a web page. */
    -webkit-tap-highlight-color: transparent;
  }

  /* Safari zooms the page when a focused input's text is under 16px. The app's
     inputs are 15px by design, so the minimum is enforced here for touch
     devices only — on a desktop the zoom never happens and the smaller size is
     the intended one. */
  @media (hover: none) and (pointer: coarse) {
    input, textarea, select { font-size: 16px !important; }
  }

  /* Reach under the notch and above the home indicator on an installed PWA. */
  body {
    padding-left: env(safe-area-inset-left);
    padding-right: env(safe-area-inset-right);
  }

  /* Keyboard focus must stay visible in a browser, where it is the only way
     some people navigate at all. */
  :focus-visible { outline: 2px solid #0080FF; outline-offset: 2px; }
  ::selection { background: #0080FF; color: #fff; }

  /* The plan of a hall is drawn on by dragging, and a browser has two habits
     that make that impossible. It starts its own drag-and-drop the moment a
     press lands on an <img>, which steals the gesture outright — that one is
     handled by taking the picture out of the hit path in the component. And on
     a touch screen it scrolls the page, which React Native's responder system
     cannot cancel once the browser has begun it. touch-action:none is the only
     way to say "this surface handles its own gestures"; there is no React
     Native style for it, so it is set here against the id the drawing surface
     carries. The img rules are belt and braces: -webkit-user-drag is the one
     Safari actually honours. */
  #blup-plan-surface {
    touch-action: none;
    -webkit-user-drag: none;
  }
  #blup-plan-surface img, #blup-plan-view img {
    -webkit-user-drag: none;
    user-select: none;
  }

  /* The same habit broke the swipe deck, and there it was worse: every card in
     Objav is mostly a poster, so the press that should start a swipe landed on
     an <img> and the browser began dragging the picture instead — a ghost of
     the cover photo following the cursor while the card itself stood still.
     Nothing in this app ever wants a picture dragged out of it, so the rule is
     global rather than another id. -webkit-user-drag is the one Safari honours;
     the draggable attribute is what everything else reads. */
  img { -webkit-user-drag: none; user-drag: none; }

  /* And on a touch screen the deck has to own its gestures, or the browser
     scrolls the page out from under a swipe that React Native has already
     claimed. */
  #blup-swipe-deck { touch-action: none; }

  /* A pointer gets a real scrollbar; a touch screen never sees one. */
  @media (hover: hover) {
    ::-webkit-scrollbar { width: 10px; height: 10px; }
    ::-webkit-scrollbar-track { background: transparent; }
    ::-webkit-scrollbar-thumb { background: #252D3D; border-radius: 999px; border: 3px solid #0A0D12; }
    ::-webkit-scrollbar-thumb:hover { background: #37415A; }
  }
`;
