import React, { useRef, useState } from 'react';
import {
  Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions,
  type GestureResponderEvent,
} from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Image } from 'expo-image';
import { useQuery, useQueryClient } from '@tanstack/react-query';

import { getEvent, updateEvent } from '@/api/events';
import { useAuth } from '@/auth/AuthProvider';
import {
  applyVenuePreset, clearVenueMapImage, cloneVenueMap, createSection, createVenueMap,
  deleteSeats, deleteSection,
  duplicateSection, generateSeats, getReusablePlans, getSectionSeats, getVenueMap,
  getVenuePresets, getVenueSections, removeVenuePlan, renameRow, setBackdropOnly, setSeatState,
  updateSection, updateVenueMap,
} from '@/api/venue';
import {
  SEAT_KIND_LABEL, SECTION_KIND_LABEL, type SeatKind, type SectionKind,
} from '@/api/seating';
import { getPlanRequest, PLAN_STATUS_LABEL, requestVenuePlan } from '@/api/venuePlans';
import { pickImage, uploadVenuePlan } from '@/storage/uploads';
import { messageFor } from '@/lib/errors';
import { formatEventDateLong } from '@/lib/format';
import { useDialog } from '@/components/Dialog';
import {
  Body, Button, Caption, Chip, Input, LoadingState, Notice, Screen, SectionHeader, Switch,
} from '@/components/ui';
import { colors, radius, spacing, typography } from '@/theme';

/**
 * Drawing the sectors.
 *
 * Drag a rectangle on the plan, name it, point it at a ticket type. The
 * rectangle is stored as fractions of the image, so the organizer can replace a
 * blurry photo of the plan with a better one later and nothing moves.
 *
 * The drag uses React Native's own responder system rather than DOM pointer
 * events, so the same code draws on a laptop with a mouse and on a phone with a
 * finger — this is a job people will do on whichever they have open.
 *
 * Three things were wrong with the first version and are fixed here.
 *
 * The plan was drawn at a fixed 0.7 aspect ratio while the buyer's screen drew
 * it at the picture's own, so every rectangle landed somewhere else for the
 * person buying than for the person who drew it. Both screens now read the
 * ratio off the map.
 *
 * A sector could be created and deleted and nothing in between — no rename, no
 * recolour, no moving it two centimetres left. Deleting one takes its seats,
 * and with them the row and number off every ticket already sold from it, so
 * "delete and draw it again" was not a workaround but a way to lose data.
 *
 * And the seat grid was generated by deleting every seat and inserting a new
 * one, from the client. That is now one guarded call in the database, which
 * refuses to remove a seat somebody has bought.
 *
 * Since then it also stopped being the organizer's screen. A plan decides what
 * is sold and for how much, and it is a couple of hours of careful work with a
 * floor plan open beside you — so BLUP draws it. This screen is for an admin;
 * everybody else gets the request form, which is the other half of the same
 * feature rather than a locked door.
 */
const PALETTE = ['#0080FF', '#FF4D8D', '#22C55E', '#FF8A3D', '#A855F7', '#22D3EE'];

const KINDS: { value: SeatKind; label: string }[] = [
  { value: 'standard', label: 'Bežné' },
  { value: 'wheelchair', label: 'Vozík' },
  { value: 'companion', label: 'Sprievod' },
  { value: 'limited_view', label: 'Výhľad' },
];

/**
 * What a sector is.
 *
 * The first five are sold and the label is what the buyer reads next to the
 * price. The last four are drawn so somebody can find themselves on the plan —
 * a hall plan without the stage on it is a grid of rectangles — and nothing
 * about them is for sale, which the database enforces rather than this screen.
 */
const SECTION_KINDS: SectionKind[] =
  ['standard', 'vip', 'box', 'standing', 'wheelchair', 'stage', 'bar', 'entrance', 'other'];

const LANDMARKS: SectionKind[] = ['stage', 'bar', 'entrance', 'other'];

export default function PlanEditorScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const queryClient = useQueryClient();
  const dialog = useDialog();
  const { width } = useWindowDimensions();
  // Full admin, not `isAdmin` — that one also covers moderators, and the
  // database asks is_full_admin(). Showing a moderator the editor would be
  // showing them a screen the server refuses every button on.
  const { profile } = useAuth();
  const canDraw = profile?.app_role === 'admin';

  /**
   * What is typed in the form, and which sector it was typed for.
   *
   * Switching sectors used to load the chosen one into the form from an effect.
   * That is a setState during an effect — a cascading render, which the React
   * Compiler rules refuse — and it also raced: a slow refetch could overwrite
   * what the organizer was in the middle of typing. So the form is derived
   * instead: the sector supplies the values until somebody types, and the
   * moment they do, their edit belongs to that sector and no other.
   */
  const [form, setForm] = useState<{
    key: string; name: string; colour: string; ticketTypeId: string | null;
    kind: SectionKind; note: string;
  } | null>(null);
  const [rows, setRows] = useState('');
  const [perRow, setPerRow] = useState('');
  /**
   * How the rows are named. A theatre letters them; a stadium numbers them and
   * often puts the sector in front — S1, C-1. Getting this wrong means a plan
   * that disagrees with the signs painted on the actual wall, and the person
   * at the door arbitrating.
   */
  const [rowStyle, setRowStyle] = useState<'letters' | 'numbers'>('letters');
  const [rowPrefix, setRowPrefix] = useState('');
  const [seatStart, setSeatStart] = useState('1');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [note, setNote] = useState<string | null>(null);

  /** The sector being edited, or null when drawing a new one. */
  const [editingId, setEditingId] = useState<string | null>(null);
  /** Seats of the sector open in the seat list, so a row can be blocked. */
  const [seatsOpen, setSeatsOpen] = useState(false);
  const [picked, setPicked] = useState<string[]>([]);

  // The rectangle being dragged, in plan pixels. Null when not dragging.
  const [draft, setDraft] = useState<{ x: number; y: number; w: number; h: number } | null>(null);
  const origin = useRef<{ x: number; y: number } | null>(null);

  /**
   * Which gesture is under way on an EXISTING sector. Null while drawing a new
   * rectangle — that is the old behaviour and it stays the default, because an
   * empty stretch of plan means "there is no sector here yet".
   *
   * Declared here with the rest of the state, not beside the handlers that use
   * it: the screen returns early while the event and the map load, and a hook
   * below that return changes the hook count between renders.
   */
  const [drag, setDrag] = useState<
    {
      mode: 'move' | 'resize' | 'rotate';
      id: string;
      x: number; y: number; w: number; h: number;
      rotation: number;
    } | null
  >(null);
  const dragStart = useRef<
    {
      x: number;
      y: number;
      rect: { x: number; y: number; w: number; h: number };
      rotation: number;
      /** Where the sector turns around, and the angle the finger started at. */
      centre: { x: number; y: number };
      pointerAngle: number;
    } | null
  >(null);

  const event = useQuery({
    queryKey: ['event', id],
    queryFn: () => getEvent(id!),
    enabled: Boolean(id),
  });

  const mapId = event.data?.venue_map_id ?? null;

  const map = useQuery({
    queryKey: ['venue', mapId],
    queryFn: () => getVenueMap(mapId!),
    enabled: Boolean(mapId),
  });

  const sections = useQuery({
    queryKey: ['venue', mapId, 'sections'],
    queryFn: () => getVenueSections(mapId!),
    enabled: Boolean(mapId),
  });

  const seats = useQuery({
    queryKey: ['venue', 'section', editingId, 'seats'],
    queryFn: () => getSectionSeats(editingId!),
    enabled: Boolean(editingId) && seatsOpen,
  });

  // Other nights in the same hall. An arena runs fifty a year on one plan, and
  // a sector is tied to a ticket type, which belongs to one event — so without
  // this the same stadium gets drawn fifty times.
  // Offered only while the event has no plan — a preset replaces a plan, and
  // replacing one would throw away sectors that tickets already point at.
  const presets = useQuery({
    queryKey: ['venue', 'presets'],
    queryFn: getVenuePresets,
    enabled: !mapId,
    staleTime: Infinity,
  });

  const reusable = useQuery({
    queryKey: ['venue', 'reusable', event.data?.organization_id, id],
    queryFn: () => getReusablePlans({
      organizationId: event.data!.organization_id!,
      excludeEventId: id!,
    }),
    enabled: Boolean(event.data?.organization_id) && !event.data?.venue_map_id,
  });

  const existing = sections.data ?? [];
  const editing = existing.find((section) => section.id === editingId) ?? null;

  const formKey = editingId ?? 'new';
  const typed = form?.key === formKey ? form : null;
  const name = typed?.name ?? editing?.name ?? '';
  const colour = typed?.colour ?? editing?.colour ?? PALETTE[0];
  const ticketTypeId = typed?.ticketTypeId ?? editing?.ticket_type_id ?? null;
  const kind: SectionKind = typed?.kind ?? editing?.kind ?? 'standard';
  const sectorNote = typed?.note ?? editing?.note ?? '';
  const isLandmark = LANDMARKS.includes(kind);

  const edit = (patch: Partial<{
    name: string; colour: string; ticketTypeId: string | null; kind: SectionKind; note: string;
  }>) =>
    setForm({ key: formKey, name, colour, ticketTypeId, kind, note: sectorNote, ...patch });

  if (event.isLoading) return <Screen><LoadingState /></Screen>;

  // Not a locked door: the other half of the same feature. An organizer says
  // what the room looks like and we draw it, which is the only version of this
  // that ends with a plan that sells the right seat at the right price.
  if (!canDraw) {
    return (
      <Screen>
        <PlanRequestForm eventId={id!} title={event.data?.title ?? null} />
      </Screen>
    );
  }

  // The EVENT's organization, not the admin's own. A plan belongs to the hall
  // it is a plan of, and its picture lands in that organization's folder —
  // filing somebody else's stadium under our own account would be quietly wrong
  // and would make the plan unreusable for the people it belongs to.
  const organizationId = event.data?.organization_id ?? null;
  const ticketTypes = event.data?.ticket_types ?? [];

  if (!organizationId) {
    return (
      <Screen>
        <Notice
          tone="warning"
          title="Event nepatrí organizácii"
          body="Plán sály patrí organizácii, aby sa dal použiť aj na ďalšie večery v tej istej sále. Tento event zatiaľ pod žiadnu nespadá."
          actionLabel="Späť na event"
          onAction={() => router.push(`/event/${id}`)}
        />
      </Screen>
    );
  }

  const planWidth = Math.min(width - spacing.gutter * 2, 720);
  // The picture's own proportions. Before the map exists there is no picture,
  // and a square is the honest guess — it is also what the table defaults to,
  // so a sector drawn now lands where it was drawn once a photo arrives.
  const ratio = map.data && map.data.image_width > 0
    ? map.data.image_height / map.data.image_width
    : 1;
  const planHeight = Math.max(160, Math.min(planWidth * ratio, 900));

  const refresh = async () => {
    await queryClient.invalidateQueries({ queryKey: ['event', id] });
    await queryClient.invalidateQueries({ queryKey: ['venue'] });
  };

  /** Creates the map on first use, so the organizer never sets one up separately. */
  const ensureMap = async (): Promise<string> => {
    if (mapId) return mapId;
    const created = await createVenueMap({
      organizationId,
      name: event.data?.venue_name || event.data?.title || 'Plán sály',
    });
    await updateEvent(id!, { venueMapId: created.id });
    await refresh();
    return created.id;
  };

  const choosePlan = async () => {
    setError(null);
    try {
      const image = await pickImage({ source: 'library' });
      if (!image) return;
      setBusy(true);
      const target = await ensureMap();
      const uploaded = await uploadVenuePlan(image.uri, organizationId);
      await updateVenueMap(target, {
        image_url: uploaded.url,
        image_width: uploaded.width,
        image_height: uploaded.height,
      });
      await refresh();
      setNote('Plán nahratý. Teraz naň ťahaním vyznač sektory.');
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  // --- drawing, moving and resizing -----------------------------------------
  const HANDLE = 30;
  /** How far above the sector the rotation knob floats. */
  const ROTATE_ARM = 34;

  /** The sector under a point, topmost first — the one drawn last wins. */
  const sectorAt = (x: number, y: number) => {
    for (let i = existing.length - 1; i >= 0; i--) {
      const section = existing[i];
      // Hit-tested against the unrotated rectangle. Exact at 0°, which is
      // almost every sector; for a turned one it is the same area seen
      // straight, which is close enough to grab and far simpler than
      // inverse-rotating every press.
      const left = section.x * planWidth;
      const top = section.y * planHeight;
      const right = left + section.width * planWidth;
      const bottom = top + section.height * planHeight;
      if (x >= left && x <= right && y >= top && y <= bottom) return section;
    }
    return null;
  };

  /** The angle from a sector's centre to a point, with "straight up" as 0°. */
  const angleFrom = (centre: { x: number; y: number }, x: number, y: number) => (
    (Math.atan2(y - centre.y, x - centre.x) * 180) / Math.PI + 90
  );

  const onStart = (e: GestureResponderEvent) => {
    const { locationX, locationY } = e.nativeEvent;

    if (editing) {
      const rect = {
        x: editing.x * planWidth,
        y: editing.y * planHeight,
        w: editing.width * planWidth,
        h: editing.height * planHeight,
      };
      const centre = { x: rect.x + rect.w / 2, y: rect.y + rect.h / 2 };
      const rotation = editing.rotation ?? 0;

      // 1. The rotation handle, floating above the top edge and turning with
      //    the sector — so it is always at the sector's "up", whatever that
      //    currently means.
      const knob = rotateAround(
        { x: centre.x, y: rect.y - ROTATE_ARM },
        centre,
        rotation,
      );
      if (Math.hypot(locationX - knob.x, locationY - knob.y) <= HANDLE) {
        dragStart.current = {
          x: locationX,
          y: locationY,
          rect,
          rotation,
          centre,
          pointerAngle: angleFrom(centre, locationX, locationY),
        };
        setDrag({ mode: 'rotate', id: editing.id, ...rect, rotation });
        return true;
      }

      // 2. The resize corner.
      const onHandle = locationX >= rect.x + rect.w - HANDLE
        && locationX <= rect.x + rect.w + HANDLE / 2
        && locationY >= rect.y + rect.h - HANDLE
        && locationY <= rect.y + rect.h + HANDLE / 2;

      if (onHandle) {
        dragStart.current = {
          x: locationX, y: locationY, rect, rotation, centre,
          pointerAngle: angleFrom(centre, locationX, locationY),
        };
        setDrag({ mode: 'resize', id: editing.id, ...rect, rotation });
        return true;
      }
    }

    // 3. An existing sector: select it and move it. Dragging a sector that is
    //    already there is what somebody expects to be able to do, and until
    //    now the only way to move one was to delete it and draw it again.
    const hit = sectorAt(locationX, locationY);
    if (hit) {
      const rect = {
        x: hit.x * planWidth,
        y: hit.y * planHeight,
        w: hit.width * planWidth,
        h: hit.height * planHeight,
      };
      const centre = { x: rect.x + rect.w / 2, y: rect.y + rect.h / 2 };
      dragStart.current = {
        x: locationX, y: locationY, rect,
        rotation: hit.rotation ?? 0,
        centre,
        pointerAngle: angleFrom(centre, locationX, locationY),
      };
      setEditingId(hit.id);
      setDraft(null);
      setDrag({ mode: 'move', id: hit.id, ...rect, rotation: hit.rotation ?? 0 });
      return true;
    }

    // 3. Empty plan: draw a new one.
    origin.current = { x: locationX, y: locationY };
    setDraft({ x: locationX, y: locationY, w: 0, h: 0 });
    return true;
  };

  const onMove = (e: GestureResponderEvent) => {
    const { locationX, locationY } = e.nativeEvent;

    if (drag && dragStart.current) {
      const from = dragStart.current;
      const dx = locationX - from.x;
      const dy = locationY - from.y;

      if (drag.mode === 'rotate') {
        // The sector follows the finger. Snapped only very near a right angle,
        // so straightening a stand is easy without the angle ever feeling
        // like it is fighting you.
        const turned = from.rotation + (angleFrom(from.centre, locationX, locationY) - from.pointerAngle);
        const wrapped = ((turned + 180) % 360 + 360) % 360 - 180;
        const nearest = Math.round(wrapped / 90) * 90;
        setDrag({
          ...drag,
          rotation: Math.abs(wrapped - nearest) <= 3 ? nearest : Math.round(wrapped * 10) / 10,
        });
        return;
      }

      if (drag.mode === 'move') {
        // Kept inside the plan: a sector half off the edge is stored as
        // fractions outside 0..1, which the database refuses anyway.
        setDrag({
          ...drag,
          x: Math.max(0, Math.min(planWidth - from.rect.w, from.rect.x + dx)),
          y: Math.max(0, Math.min(planHeight - from.rect.h, from.rect.y + dy)),
        });
      } else {
        setDrag({
          ...drag,
          w: Math.max(18, Math.min(planWidth - from.rect.x, from.rect.w + dx)),
          h: Math.max(18, Math.min(planHeight - from.rect.y, from.rect.h + dy)),
        });
      }
      return;
    }

    if (!origin.current) return;
    const start = origin.current;
    // Dragging up or left is as valid as down or right, so the rectangle is
    // normalised rather than requiring one direction.
    setDraft({
      x: Math.min(start.x, locationX),
      y: Math.min(start.y, locationY),
      w: Math.abs(locationX - start.x),
      h: Math.abs(locationY - start.y),
    });
  };

  const onEnd = () => {
    origin.current = null;

    if (drag) {
      const moved = drag;
      const from = dragStart.current;
      dragStart.current = null;
      setDrag(null);

      // A tap that selected a sector is not a move. Without this every tap
      // would write to the database and count as an edit.
      const shifted = !from
        || Math.abs(moved.x - from.rect.x) > 1 || Math.abs(moved.y - from.rect.y) > 1
        || Math.abs(moved.w - from.rect.w) > 1 || Math.abs(moved.h - from.rect.h) > 1
        || Math.abs(moved.rotation - from.rotation) > 0.05;
      if (!shifted) return;

      void (async () => {
        setError(null);
        try {
          await updateSection(moved.id, {
            x: moved.x / planWidth,
            y: moved.y / planHeight,
            width: moved.w / planWidth,
            height: moved.h / planHeight,
            rotation: moved.rotation,
          });
          await refresh();
        } catch (caught) {
          setError(messageFor(caught));
        }
      })();
      return;
    }

    // A tap is not a rectangle. Below this it was almost certainly a misfire.
    if (draft && (draft.w < 18 || draft.h < 18)) setDraft(null);
  };

  const shape = () => (draft ? {
    x: draft.x / planWidth,
    y: draft.y / planHeight,
    width: draft.w / planWidth,
    height: draft.h / planHeight,
  } : null);

  const saveSector = async () => {
    setError(null);
    setNote(null);

    if (name.trim().length < 1) { setError('Pomenuj sektor.'); return; }

    setBusy(true);
    try {
      if (editing) {
        const moved = shape();
        await updateSection(editing.id, {
          name: name.trim(),
          colour,
          kind,
          note: sectorNote,
          ticketTypeId,
          ...(moved ?? {}),
        });
        setNote(moved ? `${name} presunutý.` : `${name} upravený.`);
        setDraft(null);
        await refresh();
        await sections.refetch();
        return;
      }

      if (!draft) { setError('Najprv na pláne ťahaním vyznač obdĺžnik.'); return; }

      const target = await ensureMap();
      const created = await createSection({
        venueMapId: target,
        ticketTypeId,
        name,
        colour,
        kind,
        note: sectorNote,
        ...shape()!,
        // A landmark is drawn under the seats, or the stage covers row A.
        sortOrder: isLandmark ? -1 : existing.length,
      });

      const r = Number(rows);
      const p = Number(perRow);
      if (Number.isInteger(r) && Number.isInteger(p) && r > 0 && p > 0) {
        const made = await generateSeats({
          sectionId: created.id, rows: r, perRow: p,
          rowStyle, rowPrefix: rowPrefix.trim() || undefined,
          seatStart: Number(seatStart) || 1,
        });
        setNote(`${name} pridaný — ${made.total} miest.`);
      } else {
        setNote(`${name} pridaný — predáva sa na počet.`);
      }

      setDraft(null);
      setForm(null);
      setRows('');
      setPerRow('');
      await refresh();
      await sections.refetch();
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  /** Re-generating the grid of an existing sector. */
  const regenerate = async () => {
    if (!editing) return;
    const r = Number(rows);
    const p = Number(perRow);
    if (!Number.isInteger(r) || !Number.isInteger(p) || r < 1 || p < 1) {
      setError('Zadaj počet radov aj počet miest v rade.');
      return;
    }

    setError(null);
    setNote(null);
    setBusy(true);
    try {
      const made = await generateSeats({
        sectionId: editing.id, rows: r, perRow: p,
        rowStyle, rowPrefix: rowPrefix.trim() || undefined,
        seatStart: Number(seatStart) || 1,
      });
      setNote(
        made.removed > 0
          ? `${editing.name}: ${made.total} miest (${made.created} pribudlo, ${made.removed} ubudlo).`
          : `${editing.name}: ${made.total} miest, ${made.created} pribudlo.`,
      );
      await refresh();
      await sections.refetch();
      await seats.refetch();
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  /**
   * Deleting seats that are not there — a pillar in the middle, a gangway.
   *
   * Different from taking them out of sale, and the difference matters on the
   * plan: a seat that exists and is not sold stays visible, because the person
   * beside it can see it is empty. A seat that does not exist should be gone.
   */
  const removePicked = async () => {
    if (picked.length === 0) { setError('Najprv klepni na miesta, ktorých sa to týka.'); return; }

    const sure = await dialog.confirm({
      title: `Zmazať ${picked.length} ${picked.length === 1 ? 'miesto' : 'miest'}?`,
      body: 'Použi to tam, kde miesto naozaj nie je — stĺp, priechod. Ak sa má len prestať predávať, '
        + 'vyber „Stiahnuť z predaja": zostane na pláne a je vidieť, že je prázdne.',
      confirmLabel: 'Zmazať',
      destructive: true,
    });
    if (!sure) return;

    setError(null);
    setNote(null);
    setBusy(true);
    try {
      const gone = await deleteSeats(picked);
      setNote(`Zmazaných miest: ${gone}.`);
      setPicked([]);
      await seats.refetch();
      await refresh();
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  /** Renames one row in place, so tickets already sold keep their seat. */
  const renameOneRow = async (label: string) => {
    const next = await dialog.prompt({
      title: `Premenovať rad ${label}`,
      body: 'Miesta si zachovajú identitu, takže predané vstupenky zostanú na svojich sedadlách.',
      initialValue: label,
      confirmLabel: 'Premenovať',
    });
    if (!next || next.trim() === label) return;

    setError(null);
    setNote(null);
    setBusy(true);
    try {
      const changed = await renameRow(editing!.id, label, next.trim());
      setNote(`Rad ${label} sa teraz volá ${next.trim()} (${changed} miest).`);
      await seats.refetch();
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  /**
   * Not called `usePreset`: a name starting with `use` is a hook to the lint
   * rule, which then reports a rules-of-hooks violation that is not there.
   * The same trap already caught `useFreeBoost` on the promo screen.
   */
  const applyPreset = async (code: string) => {
    if (!id) return;
    setError(null);
    setNote(null);
    setBusy(true);
    try {
      await applyVenuePreset(id, code);
      await refresh();
      setNote('Hala je nakreslená. Teraz už len názvy, rady a typy vstupeniek.');
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  const toggleBackdrop = async (backdropOnly: boolean) => {
    if (!mapId) return;
    setError(null);
    setBusy(true);
    try {
      await setBackdropOnly(mapId, backdropOnly);
      await queryClient.invalidateQueries({ queryKey: ['venue', mapId] });
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  /** A copy of this sector: same size, rotation and seat layout. */
  const copySector = async () => {
    if (!editing) return;
    setError(null);
    setNote(null);
    setBusy(true);
    try {
      const copy = await duplicateSection(editing.id);
      setNote(`Hotovo — „${copy.name}". Typ vstupenky jej ešte vyber.`);
      await refresh();
      setEditingId(copy.id);
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  /** Turns the sector by a fixed step. */
  const rotateBy = async (degrees: number) => {
    if (!editing) return;
    setError(null);
    setBusy(true);
    try {
      const next = Math.round((((editing.rotation ?? 0) + degrees + 180) % 360 + 360) % 360 - 180);
      await updateSection(editing.id, { rotation: next });
      await refresh();
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  const applyToPicked = async (patch: { sellable?: boolean; kind?: SeatKind }) => {
    if (picked.length === 0) { setError('Najprv klepni na miesta, ktorých sa to týka.'); return; }
    setError(null);
    setNote(null);
    setBusy(true);
    try {
      const changed = await setSeatState(picked, patch);
      setNote(`Upravených miest: ${changed}.`);
      setPicked([]);
      await seats.refetch();
      await refresh();
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  const remove = async (sectionId: string, sectionName: string) => {
    const ok = await dialog.confirm({
      title: `Zmazať ${sectionName}?`,
      body: 'Zmažú sa aj všetky jeho miesta. Ak sú z neho predané vstupenky, zostanú bez miesta — '
          + 'radšej sektor uprav, než aby si ho mazal.',
      confirmLabel: 'Zmazať',
      destructive: true,
    });
    if (!ok) return;

    setBusy(true);
    try {
      await deleteSection(sectionId);
      if (editingId === sectionId) setEditingId(null);
      await sections.refetch();
      await refresh();
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  const copyPlan = async (sourceMapId: string, fromTitle: string) => {
    const ok = await dialog.confirm({
      title: `Skopírovať plán z „${fromTitle}“?`,
      body: 'Sektory aj miesta sa prenesú a napoja sa na typy vstupeniek tohto eventu '
          + 'podľa názvu. Čo sa nenapáruje, ostane bez ceny.',
      confirmLabel: 'Skopírovať',
    });
    if (!ok) return;

    setError(null);
    setNote(null);
    setBusy(true);
    try {
      await cloneVenueMap({ sourceMapId, eventId: id! });
      await refresh();
      setNote('Plán je skopírovaný. Skontroluj, či sú sektory napojené na správne vstupenky.');
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  const dropImage = async () => {
    if (!mapId) return;
    const ok = await dialog.confirm({
      title: 'Zmazať obrázok plánu?',
      body: 'Sektory ani miesta sa nikam nepohnú — sú uložené ako podiely obrázka, '
          + 'nie ako body. Môžeš rovno nahrať lepšiu fotku.',
      confirmLabel: 'Zmazať obrázok',
      destructive: true,
    });
    if (!ok) return;

    setError(null);
    setNote(null);
    setBusy(true);
    try {
      await clearVenueMapImage(mapId);
      await refresh();
      setNote('Obrázok zmazaný. Sektory zostali tam, kde boli.');
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  const dropPlan = async () => {
    const soldFrom = existing.some((section) => section.numbered);
    const ok = await dialog.confirm({
      title: 'Odpojiť plán od eventu?',
      body: soldFrom
        ? 'Event sa vráti k predaju na počet. Plán zostane uložený a vstupenky, ktoré '
          + 'už majú miesto, si ho nechajú.'
        : 'Event sa vráti k predaju na počet. Ak plán nepoužíva žiadny iný event, zmaže sa.',
      confirmLabel: 'Odpojiť',
      destructive: true,
    });
    if (!ok) return;

    setError(null);
    setNote(null);
    setBusy(true);
    try {
      // keepPlan: never destroy a hall somebody may run again next month from
      // a button whose word was "odpojiť". Deleting an unused one is what the
      // database does by itself when nothing points at it.
      const result = await removeVenuePlan({ eventId: id!, keepPlan: false });
      setEditingId(null);
      await refresh();
      setNote(
        result.deleted
          ? 'Plán zmazaný — nepoužíval ho žiadny iný event.'
          : result.used_elsewhere
            ? 'Plán odpojený. Zostal uložený, lebo ho používa aj iný event.'
            : 'Plán odpojený a zostal uložený.',
      );
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  const startNew = () => {
    setEditingId(null);
    setSeatsOpen(false);
    setPicked([]);
    setForm(null);
    setRows('');
    setPerRow('');
    setDraft(null);
  };

  return (
    <Screen scroll>
      <Text style={styles.title}>Plán sály</Text>
      <Body muted style={styles.intro}>
        Vyber si hotovú halu a uprav ju, alebo nahraj obrázok a obkresli si ju sám.
        Obrázok je len podklad: kupujúcemu sa neposiela, ten uvidí sektory, ktoré si
        podľa neho nakreslil. Sektor bez miest sa predáva na počet, sektor s radmi
        po jednotlivých sedadlách.
      </Body>

      {error ? <Notice tone="danger" title="Nedá sa" body={error} /> : null}
      {note ? <Notice tone="success" title="Hotovo" body={note} /> : null}

      {/* The quickest way in: pick the shape, then edit only what is actually
          different about this hall — the names, the rows and which ticket type
          sells in which sector. */}
      {!mapId && (presets.data ?? []).length > 0 ? (
        <>
          <SectionHeader title="Začni z hotovej haly" />
          <Caption style={styles.hint}>
            Nakreslí tvar za teba. Sektor dostane cenu, len keď sa jeho názov
            presne zhoduje s typom vstupenky — hádať podľa poradia by predalo
            lacné miesta za drahé.
          </Caption>
          {(presets.data ?? []).map((preset) => (
            <Pressable
              key={preset.code}
              style={styles.row}
              onPress={() => applyPreset(preset.code)}
              disabled={busy}
            >
              <View style={styles.presetShape}>
                {preset.sections.map((section) => (
                  <View
                    key={section.name}
                    style={{
                      position: 'absolute',
                      left: `${section.x * 100}%`,
                      top: `${section.y * 100}%`,
                      width: `${section.width * 100}%`,
                      height: `${section.height * 100}%`,
                      borderRadius: 2,
                      backgroundColor: `${section.colour}66`,
                      borderWidth: 1,
                      borderColor: section.colour,
                    }}
                  />
                ))}
              </View>
              <View style={styles.flex}>
                <Text style={styles.rowName}>{preset.name}</Text>
                <Caption>{preset.description}</Caption>
              </View>
              <Text style={styles.presetArrow}>→</Text>
            </Pressable>
          ))}
        </>
      ) : null}

      <Button
        title={map.data?.image_url ? 'Vymeniť obrázok haly' : 'Nahrať obrázok haly'}
        variant="secondary"
        onPress={choosePlan}
        loading={busy}
      />

      {/* Almost always a backdrop, which is why that is the default. The
          exception is an official seating chart the venue publishes anyway —
          then showing it to buyers helps rather than leaking a photo of
          somebody's desk. */}
      {map.data?.image_url ? (
        <View style={styles.backdrop}>
          <Switch
            value={map.data.image_is_backdrop ?? true}
            onValueChange={(next) => void toggleBackdrop(next)}
            label="Obrázok je len podklad na kreslenie"
            description={
              map.data.image_is_backdrop ?? true
                ? 'Kupujúcemu sa neposiela — uvidí len sektory, ktoré si nakreslil.'
                : 'Obrázok sa zobrazí aj kupujúcim pod sektormi. Zapni to len pri oficiálnom pláne sály.'
            }
          />
        </View>
      ) : null}

      {!mapId && (reusable.data ?? []).length > 0 ? (
        <>
          <SectionHeader title="Alebo skopíruj plán, ktorý už existuje" />
          <Caption style={styles.hint}>
            Sektory sa napoja na typy vstupeniek tohto eventu podľa názvu — „VIP“ nájde
            „VIP“. Čo sa nenapáruje, príde bez ceny a napojíš to ručne. Miesta sa skopírujú
            aj s tým, ktoré sú pre vozík a ktoré za stĺpom: to je vlastnosť sály, nie večera.
          </Caption>
          {(reusable.data ?? []).map((plan) => (
            <View key={plan.event_id} style={styles.row}>
              <View style={styles.flex}>
                <Text style={styles.rowName} numberOfLines={1}>{plan.title}</Text>
                <Caption>{formatEventDateLong(plan.start_at)}</Caption>
              </View>
              <Button
                title="Skopírovať"
                variant="secondary"
                compact
                disabled={busy}
                onPress={() => copyPlan(plan.venue_map_id, plan.title)}
              />
            </View>
          ))}
        </>
      ) : null}

      <View
        style={[styles.plan, { width: planWidth, height: planHeight }]}
        nativeID="blup-plan-surface"
        onStartShouldSetResponder={onStart}
        onMoveShouldSetResponder={() => true}
        onResponderMove={onMove}
        onResponderRelease={onEnd}
      >
        {map.data?.image_url ? (
          // pointerEvents="none" is load-bearing, not tidiness. expo-image
          // renders an <img> on web, and a browser's own drag-and-drop for
          // images fires on mousedown — so pressing on the plan started
          // dragging the picture instead of drawing a rectangle, and the
          // responder never saw the gesture at all. With the image out of the
          // hit path the press lands on the View below, which is the one doing
          // the drawing.
          <View style={StyleSheet.absoluteFill} pointerEvents="none">
            <Image
              source={{ uri: map.data.image_url }}
              style={StyleSheet.absoluteFill}
              contentFit="contain"
            />
          </View>
        ) : existing.length === 0 ? (
          // Only while the plan really is empty. It used to print over the
          // middle of the surface whatever was on it, so on a stadium it ran
          // straight across the pitch and through two sector names — saying
          // "you can draw without a picture" to somebody who already had.
          <View style={styles.planEmpty} pointerEvents="none">
            <Caption>Bez obrázka — kresli voľne.</Caption>
          </View>
        ) : null}

        {existing.map((section) => {
          // While a sector is being dragged it is drawn from the gesture, not
          // from what is stored — otherwise it would snap back on every frame
          // until the save landed.
          const live = drag?.id === section.id ? drag : null;
          const left = live ? live.x : section.x * planWidth;
          const top = live ? live.y : section.y * planHeight;
          const width = live ? live.w : section.width * planWidth;
          const height = live ? live.h : section.height * planHeight;

          return (
            <View
              key={section.id}
              pointerEvents="none"
              style={[styles.sector, {
                left,
                top,
                width,
                height,
                borderColor: section.colour,
                backgroundColor: `${section.colour}2E`,
                // Drawn at the angle it is stored at, otherwise the editor and
                // the buyer's plan disagree about the same hall.
                transform: [{ rotate: `${live ? live.rotation : (section.rotation ?? 0)}deg` }],
              }, section.id === editingId && styles.sectorEditing]}
            >
              <Text style={styles.sectorName} numberOfLines={1}>{section.name}</Text>
            </View>
          );
        })}

        {/* The two handles of the sector being edited, drawn outside its own
            view: a handle inside a rotated element rotates with it, and its
            hit box then no longer matches where it appears. These are placed
            in plan coordinates and turned by hand, so what you press is what
            you see. */}
        {editing ? (() => {
          const live = drag?.id === editing.id ? drag : null;
          const rect = {
            x: live ? live.x : editing.x * planWidth,
            y: live ? live.y : editing.y * planHeight,
            w: live ? live.w : editing.width * planWidth,
            h: live ? live.h : editing.height * planHeight,
          };
          const rotation = live ? live.rotation : (editing.rotation ?? 0);
          const centre = { x: rect.x + rect.w / 2, y: rect.y + rect.h / 2 };
          const knob = rotateAround({ x: centre.x, y: rect.y - ROTATE_ARM }, centre, rotation);
          const corner = rotateAround({ x: rect.x + rect.w, y: rect.y + rect.h }, centre, rotation);

          return (
            <>
              <View
                pointerEvents="none"
                style={[styles.handle, styles.knob, {
                  left: knob.x - 14,
                  top: knob.y - 14,
                  borderColor: editing.colour,
                }]}
              >
                <Text style={styles.knobGlyph}>↻</Text>
              </View>

              <View
                pointerEvents="none"
                style={[styles.handle, {
                  left: corner.x - 14,
                  top: corner.y - 14,
                  borderColor: editing.colour,
                }]}
              />

              {/* The angle while it turns, because a degree read off a
                  rectangle by eye is a guess. */}
              {live?.mode === 'rotate' ? (
                <View pointerEvents="none" style={[styles.angle, { left: centre.x - 28, top: centre.y - 12 }]}>
                  <Text style={styles.angleText}>{Math.round(live.rotation)}°</Text>
                </View>
              ) : null}
            </>
          );
        })() : null}

        {draft ? (
          <View
            pointerEvents="none"
            style={[styles.draft, {
              left: draft.x, top: draft.y, width: draft.w, height: draft.h, borderColor: colour,
            }]}
          />
        ) : null}
      </View>

      <Caption style={styles.hint}>
        {draft
          ? editing
            ? `Nový obdĺžnik pre ${editing.name}. Ulož a sektor sa presunie.`
            : 'Obdĺžnik je vyznačený. Pomenuj ho nižšie a ulož.'
          : 'Ťahaj po pláne a vyznač obdĺžnik sektora.'}
      </Caption>

      {/* --- the form: one sector at a time, new or existing ------------------ */}
      <SectionHeader
        title={editing ? `Upraviť · ${editing.name}` : 'Nový sektor'}
        action={editing ? 'Nový sektor' : undefined}
        onAction={editing ? startNew : undefined}
      />

      <Input label="Názov" value={name} onChangeText={(next) => edit({ name: next })} placeholder="Napr. Tribúna A" editable={!busy} />

      <Caption style={styles.label}>Farba</Caption>
      <View style={styles.palette}>
        {PALETTE.map((c) => (
          <Pressable
            key={c}
            onPress={() => edit({ colour: c })}
            accessibilityRole="button"
            accessibilityLabel={`Farba ${c}`}
            style={[styles.swatch, { backgroundColor: c }, colour === c && styles.swatchOn]}
          />
        ))}
      </View>

      <Caption style={styles.label}>Čo to je</Caption>
      <View style={styles.chips}>
        {SECTION_KINDS.map((option) => (
          <Chip
            key={option}
            label={SECTION_KIND_LABEL[option]}
            selected={kind === option}
            onPress={() => edit({ kind: option })}
          />
        ))}
      </View>
      <Caption style={styles.hint}>
        {isLandmark
          ? 'Orientačný bod — nakreslí sa na plán, aby sa kupujúci vedel zorientovať, '
            + 'ale nepredáva sa a typ vstupenky nemá.'
          : 'Predáva sa. Názov druhu uvidí kupujúci vedľa ceny.'}
      </Caption>

      <Input
        label="Poznámka pre kupujúceho (nepovinné)"
        value={sectorNote}
        onChangeText={(next) => edit({ note: next })}
        placeholder="Napr. Vlastný vstup, obsluha pri stole"
        maxLength={200}
        editable={!busy}
      />

      {isLandmark ? null : (
        <>
      <Caption style={styles.label}>Ktorý typ vstupenky sa v ňom predáva</Caption>
      {ticketTypes.length === 0 ? (
        <Notice
          tone="warning"
          title="Event nemá typy vstupeniek"
          body="Sektor predáva niektorý z nich, takže ich najprv doplň v úprave eventu."
          actionLabel="Upraviť event"
          onAction={() => router.push(`/event/edit/${id}`)}
        />
      ) : (
        <View style={styles.chips}>
          {ticketTypes.map((type) => (
            <Chip
              key={type.id}
              label={type.name}
              selected={ticketTypeId === type.id}
              onPress={() => edit({ ticketTypeId: ticketTypeId === type.id ? null : type.id })}
            />
          ))}
        </View>
      )}

        </>
      )}

      <Caption style={styles.label}>
        {editing && editing.numbered ? 'Prekresliť rady a miesta' : 'Číslované sedenie (nepovinné)'}
      </Caption>
      <View style={styles.seatRow}>
        <View style={styles.flex}>
          <Input label="Radov" value={rows} onChangeText={setRows} placeholder="10" keyboardType="number-pad" editable={!busy} />
        </View>
        <View style={styles.flex}>
          <Input label="Miest v rade" value={perRow} onChangeText={setPerRow} placeholder="20" keyboardType="number-pad" editable={!busy} />
        </View>
      </View>
      {/* How the rows are called. Not a detail: a plan whose rows disagree with
          the signs painted on the wall leaves the person at the door
          arbitrating between a ticket and a doorframe. */}
      <Caption style={styles.label}>Ako sa volajú rady</Caption>
      <View style={styles.chips}>
        <Chip
          label="A, B, C…"
          selected={rowStyle === 'letters'}
          onPress={() => setRowStyle('letters')}
        />
        <Chip
          label="1, 2, 3…"
          selected={rowStyle === 'numbers'}
          onPress={() => setRowStyle('numbers')}
        />
      </View>
      <View style={styles.seatRow}>
        <View style={styles.flex}>
          <Input
            label="Predpona radu"
            value={rowPrefix}
            onChangeText={setRowPrefix}
            placeholder="napr. S"
            maxLength={4}
            editable={!busy}
          />
        </View>
        <View style={styles.flex}>
          <Input
            label="Prvé miesto"
            value={seatStart}
            onChangeText={setSeatStart}
            placeholder="1"
            keyboardType="number-pad"
            editable={!busy}
          />
        </View>
      </View>

      <Caption style={styles.hint}>
        {`Prvý rad bude „${rowPrefix.trim()}${rowStyle === 'numbers' ? '1' : 'A'}", prvé miesto ${Number(seatStart) || 1}.`}
        {' Nechaj rady a miesta prázdne a sektor sa bude predávať na počet.'}
        {' Miesta, ktoré už niekto kúpil, sa prekreslením nezmažú — ak by sa mali, plán to odmietne.'}
      </Caption>

      <Button
        title={editing ? 'Uložiť zmeny' : 'Uložiť sektor'}
        onPress={saveSector}
        loading={busy}
        disabled={!editing && !draft}
      />

      {editing ? (
        <>
          {/* Turned by dragging the ↻ knob above the sector — any angle, not a
              list of them. The buttons stay for the two things a hand is bad
              at: an exact quarter turn, and getting back to straight. */}
          <Caption style={styles.label}>
            Otočenie: {Math.round(editing.rotation ?? 0)}° — ťahaj za ↻ nad sektorom
          </Caption>
          <View style={styles.actions}>
            <Button title="↺ 90°" variant="secondary" compact onPress={() => rotateBy(-90)} disabled={busy} />
            <Button title="↻ 90°" variant="secondary" compact onPress={() => rotateBy(90)} disabled={busy} />
            <Button title="Narovnať" variant="ghost" compact onPress={() => rotateBy(-(editing.rotation ?? 0))} disabled={busy} />
          </View>

          <Button
            title="Kópia sektora"
            variant="secondary"
            onPress={copySector}
            loading={busy}
          />
          <Caption style={styles.hint}>
            Rovnaká veľkosť, farba, otočenie aj rozloženie miest — štadión má
            štyri rovnaké tribúny. Typ vstupenky kópia nedostane: dva sektory
            predávajúce ten istý sklad by predali jedno miesto dvakrát.
          </Caption>

          <Button
            title="Prekresliť miesta"
            variant="secondary"
            onPress={regenerate}
            loading={busy}
          />
          <Button
            title={seatsOpen ? 'Skryť miesta' : 'Upraviť jednotlivé miesta'}
            variant="ghost"
            onPress={() => setSeatsOpen(!seatsOpen)}
            disabled={!editing.numbered}
          />
        </>
      ) : null}

      {/* --- single seats ---------------------------------------------------- */}
      {editing && seatsOpen ? (
        <>
          <SectionHeader title={`${editing.name} · miesta`} />
          <Caption style={styles.hint}>
            Klepni na miesta a potom povedz, čo s nimi. Predané miesto sa nedá stiahnuť z predaja —
            plán by potom klamal.
          </Caption>

          {seats.isLoading ? <LoadingState label="Načítavam miesta…" /> : null}

          <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.seatScroll}>
            <View>
              {groupRows(seats.data ?? []).map(([label, inRow]) => (
                <View key={label} style={styles.seatLine}>
                  {/* The row's own name is the button that renames it. */}
                  <Pressable onPress={() => renameOneRow(label)} disabled={busy} hitSlop={6}>
                    <Text style={[styles.seatRowLabel, styles.seatRowLabelTap]}>{label}</Text>
                  </Pressable>
                  {inRow.map((seat) => {
                    const on = picked.includes(seat.id);
                    return (
                      <Pressable
                        key={seat.id}
                        onPress={() => setPicked(
                          on ? picked.filter((s) => s !== seat.id) : [...picked, seat.id],
                        )}
                        accessibilityRole="button"
                        accessibilityState={{ selected: on }}
                        accessibilityLabel={
                          `Rad ${seat.row_label}, miesto ${seat.seat_number}, `
                          + `${SEAT_KIND_LABEL[seat.kind as SeatKind] ?? seat.kind}`
                          + `${seat.is_sellable ? '' : ', mimo predaja'}`
                        }
                        style={[
                          styles.seatChip,
                          !seat.is_sellable && styles.seatChipOff,
                          seat.kind !== 'standard' && styles.seatChipKind,
                          on && styles.seatChipOn,
                        ]}
                      >
                        <Text style={styles.seatChipLabel}>{seat.seat_number}</Text>
                      </Pressable>
                    );
                  })}
                </View>
              ))}
            </View>
          </ScrollView>

          <Caption style={styles.label}>Vybraných miest: {picked.length}</Caption>

          <View style={styles.actions}>
            <Button title="Stiahnuť z predaja" variant="secondary" compact onPress={() => applyToPicked({ sellable: false })} disabled={busy} />
            <Button title="Vrátiť do predaja" variant="secondary" compact onPress={() => applyToPicked({ sellable: true })} disabled={busy} />
            {/* For a seat that is not there at all. Out of sale keeps it on the
                plan, which is right for a held-back seat and wrong for a
                pillar. */}
            <Button title="Zmazať miesta" variant="danger" compact onPress={removePicked} disabled={busy} />
          </View>

          <Caption style={styles.label}>Čo sú to za miesta</Caption>
          <View style={styles.chips}>
            {KINDS.map((kind) => (
              <Chip
                key={kind.value}
                label={kind.label}
                onPress={() => applyToPicked({ kind: kind.value })}
              />
            ))}
          </View>
        </>
      ) : null}

      {/* --- the list -------------------------------------------------------- */}
      {existing.length > 0 ? (
        <>
          <SectionHeader title={`Sektory · ${existing.length}`} />
          {existing.map((section) => (
            <View key={section.id} style={styles.row}>
              <View style={[styles.dot, { backgroundColor: section.colour }]} />
              <View style={styles.flex}>
                <Text style={styles.rowName}>{section.name}</Text>
                <Caption>
                  {SECTION_KIND_LABEL[section.kind] ?? section.kind}
                  {section.landmark
                    ? ' · nepredáva sa'
                    : section.numbered
                      ? ` · číslované, ${section.seat_count} miest`
                      : ' · predaj na počet'}
                </Caption>
              </View>
              <Button
                title={section.id === editingId ? 'Upravuje sa' : 'Upraviť'}
                variant="ghost"
                compact
                onPress={() => { setEditingId(section.id); setSeatsOpen(false); }}
                disabled={busy}
              />
              <Button title="Zmazať" variant="ghost" compact onPress={() => remove(section.id, section.name)} disabled={busy} />
            </View>
          ))}
        </>
      ) : null}

      <Button
        title="Pozrieť ako kupujúci"
        variant="ghost"
        onPress={() => router.push(`/event/seats/${id}`)}
        disabled={existing.length === 0}
      />

      {mapId ? (
        <>
          <SectionHeader title="Zahodiť" />
          <Caption style={styles.hint}>
            Zlá fotka sa dá vymeniť bez toho, aby sa sektory pohli — sú uložené ako
            podiely obrázka. Odpojenie plánu vráti event k predaju na počet; predané
            vstupenky si svoje miesto nechajú.
          </Caption>
          <View style={styles.actions}>
            <Button
              title="Zmazať obrázok"
              variant="secondary"
              compact
              onPress={dropImage}
              disabled={busy || !map.data?.image_url}
            />
            <Button
              title="Odpojiť plán od eventu"
              variant="danger"
              compact
              onPress={dropPlan}
              disabled={busy}
            />
          </View>
        </>
      ) : null}
    </Screen>
  );
}

/**
 * The organizer's half of the feature: describing the room.
 *
 * Deliberately one long field rather than a form of rows and columns. A hall is
 * described in sentences — "štyri tribúny po desať radov, pódium na severnej
 * strane, prvé dva rady VIP" — and a set of number inputs would collect less
 * than that while looking like it collected everything.
 */
function PlanRequestForm({ eventId, title }: { eventId: string; title: string | null }) {
  const [text, setText] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const existing = useQuery({
    queryKey: ['venue', 'request', eventId],
    queryFn: () => getPlanRequest(eventId),
  });

  if (existing.isLoading) return <LoadingState />;

  const request = existing.data;

  const send = async () => {
    setError(null);
    if (text.trim().length < 20) {
      setError('Napíš aspoň pár viet — koľko radov, kde je pódium, čo je VIP.');
      return;
    }

    setBusy(true);
    try {
      await requestVenuePlan({ eventId, note: text.trim() });
      setText('');
      await existing.refetch();
    } catch (caught) {
      setError(messageFor(caught));
    } finally {
      setBusy(false);
    }
  };

  return (
    <>
      <Text style={styles.title}>Plán sály</Text>
      <Body muted style={styles.intro}>
        {title
          ? `Predaj po sektoroch a konkrétnych miestach pre „${title}“.`
          : 'Predaj po sektoroch a konkrétnych miestach.'}
        {' '}Plán kreslíme my — sektor o pár pixelov vedľa predá iné miesto, než na ktoré
        sa kupujúci pozeral, a zle napojený sektor predá inú cenu. Napíš nám, ako sála
        vyzerá, a nachystáme to.
      </Body>

      {error ? <Notice tone="danger" title="Nedá sa" body={error} /> : null}

      {request ? (
        <Notice
          tone={request.status === 'done' ? 'success' : request.status === 'rejected' ? 'warning' : 'accent'}
          title={PLAN_STATUS_LABEL[request.status]}
          body={
            request.admin_note
              ?? (request.status === 'done'
                ? 'Miesta sú nachystané. Pozri sa na plán tak, ako ho uvidí kupujúci, '
                  + 'a ozvi sa nám, ak niečo nesedí.'
                : 'Máme to u seba. Ozveme sa, keď to bude hotové.')
          }
          // Checking it is the organizer's job even though drawing it is not,
          // and the buyer's own screen is the honest way to check: it shows
          // exactly what somebody buying a ticket will see.
          actionLabel={request.status === 'done' ? 'Pozrieť ako kupujúci' : undefined}
          onAction={request.status === 'done'
            ? () => router.push(`/event/seats/${eventId}`)
            : undefined}
        />
      ) : null}

      {request && request.status !== 'rejected' ? (
        <>
          <SectionHeader title="Čo si nám napísal" />
          <Body muted>{request.note}</Body>
        </>
      ) : (
        <>
          <Input
            label="Ako sála vyzerá"
            value={text}
            onChangeText={setText}
            placeholder={'Napr. Štyri tribúny po 10 radov × 20 miest, pódium na severnej '
              + 'strane, plocha pred pódiom na státie, prvé dva rady VIP s vlastným vstupom.'}
            multiline
            numberOfLines={8}
            maxLength={2000}
            style={styles.requestInput}
            editable={!busy}
          />
          <Caption style={styles.hint}>
            Ak máš plán sály ako obrázok alebo PDF, spomeň to — vypýtame si ho.
            Stačí aj odfotený papier; obrázok je len podklad, dôležité sú sektory,
            ktoré naň nakreslíme.
          </Caption>
          <Button title="Požiadať o plán sály" onPress={send} loading={busy} />
        </>
      )}
    </>
  );
}

/** Turns a point around a centre by `degrees`, which is what a rotated
 *  sector's handles need: they have to sit where the sector's corners are
 *  drawn, not where its unrotated rectangle is. */
function rotateAround(
  point: { x: number; y: number },
  centre: { x: number; y: number },
  degrees: number,
): { x: number; y: number } {
  const radians = (degrees * Math.PI) / 180;
  const dx = point.x - centre.x;
  const dy = point.y - centre.y;
  return {
    x: centre.x + dx * Math.cos(radians) - dy * Math.sin(radians),
    y: centre.y + dx * Math.sin(radians) + dy * Math.cos(radians),
  };
}

/** Seats grouped by row, in the order the rows are lettered. */
function groupRows<T extends { row_label: string; seat_number: number }>(seats: T[]): [string, T[]][] {
  const byRow = new Map<string, T[]>();
  for (const seat of seats) {
    const bucket = byRow.get(seat.row_label);
    if (bucket) bucket.push(seat);
    else byRow.set(seat.row_label, [seat]);
  }
  return [...byRow.entries()]
    .sort((a, b) => (a[0].length - b[0].length) || a[0].localeCompare(b[0], 'sk'))
    .map(([label, inRow]) => [label, [...inRow].sort((a, b) => a.seat_number - b.seat_number)]);
}

const styles = StyleSheet.create({
  title: { ...typography.title, color: colors.text },
  backdrop: { marginBottom: spacing.md },
  presetShape: {
    width: 64,
    height: 48,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  presetArrow: { ...typography.rowTitle, color: colors.accent },
  intro: { marginTop: spacing.xs, marginBottom: spacing.lg },
  flex: { flex: 1, minWidth: 0 },
  label: { marginTop: spacing.md, marginBottom: spacing.xs },
  hint: { marginTop: spacing.xs, marginBottom: spacing.md },

  plan: {
    alignSelf: 'center',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    marginTop: spacing.md,
    // Dragging across a surface selects the text on it in a browser, which
    // leaves the sector labels highlighted in blue behind the rectangle being
    // drawn. Harmless and it looks broken.
    userSelect: 'none',
  },
  planEmpty: {
    position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
    alignItems: 'center', justifyContent: 'center', padding: spacing.lg,
  },

  sector: { position: 'absolute', borderWidth: 2, borderRadius: radius.sm, alignItems: 'center', justifyContent: 'center' },
  handle: {
    position: 'absolute',
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 2,
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  knob: { alignItems: 'center', justifyContent: 'center' },
  knobGlyph: { fontSize: 15, color: colors.page },
  angle: {
    position: 'absolute',
    width: 56,
    alignItems: 'center',
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: 'rgba(10,13,18,0.85)',
  },
  angleText: { ...typography.monoStrong, color: '#FFFFFF' },
  sectorEditing: { borderStyle: 'dashed', borderWidth: 3 },
  sectorName: { color: colors.text, fontWeight: '700', fontSize: 12 },
  draft: { position: 'absolute', borderWidth: 2, borderStyle: 'dashed', borderRadius: radius.sm },

  palette: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm },
  swatch: { width: 30, height: 30, borderRadius: 15, borderWidth: 2, borderColor: 'transparent' },
  swatchOn: { borderColor: colors.text },

  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginBottom: spacing.sm },
  seatRow: { flexDirection: 'row', gap: spacing.sm },
  actions: { flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm },

  seatScroll: { marginVertical: spacing.sm },
  seatLine: { flexDirection: 'row', alignItems: 'center', gap: 4, marginBottom: 4 },
  seatRowLabelTap: { textDecorationLine: 'underline' },
  seatRowLabel: { ...typography.caption, color: colors.textSecondary, width: 26 },
  seatChip: {
    minWidth: 30, height: 30, borderRadius: radius.sm,
    alignItems: 'center', justifyContent: 'center',
    borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface,
    paddingHorizontal: 4,
  },
  seatChipOn: { borderColor: colors.accent, backgroundColor: colors.accentSoft },
  seatChipOff: { opacity: 0.4, borderStyle: 'dashed' },
  seatChipKind: { borderColor: colors.warning },
  seatChipLabel: { ...typography.caption, color: colors.text },

  row: {
    flexDirection: 'row', alignItems: 'center', gap: spacing.md,
    padding: spacing.md, borderRadius: radius.md,
    backgroundColor: colors.surface, marginBottom: spacing.sm,
  },
  dot: { width: 14, height: 14, borderRadius: 7 },
  rowName: { ...typography.bodyStrong, color: colors.text },
  requestInput: { minHeight: 160, textAlignVertical: 'top' },
});
